/**********************************************************************/
/*                                                                    */
/*  RWL - A demonstration program placed in the Public Domain         */
/*        by it author, R L Walsh, June 10, 2000                      */
/*                                                                    */
/**********************************************************************/

//  RWLX.H

/**********************************************************************/

// dialog IDs

#define IDD_MAIN    101
#define IDD_ERRBOX  109

#define IDC_SET     201
#define IDC_UNDO    202
#define IDC_BEG     203
#define IDC_END     204

#define IDC_MLE     211
#define IDC_CAP     212
#define IDC_PIDLB   213
#define IDC_PIDSET  214
#define IDC_PIDUPDT 215

/**********************************************************************/

